# Image Sets
#
# Worker Manager providers spawn worker instances for a given worker pool from
# pre-created machine images whose image names are specified in the worker pool
# definition. Some cloud providers (such as AWS) require region-specific
# machine images. An image set represents the set of (equivalent) images for a
# given cloud provider, together with associated worker config.
#
#
# Format of imagesets.yml
#
# Each image set is keyed by a consice descriptive name, which is referenced
# from projects.yml (`imageset` key).
#
# The format of the image set configuration is as follows:
#
# <image-set-name>:
#   <cloud>:              <cloud> is the name of a @cloud annotated function in
#                         `generate/workers.py` (`aws`/`gcp`). The value
#                         underneath the key depends on the cloud (see below).
#   workerImplementation: the name of a @worker_pool_type annotated function in
#                         `generate/workers.py` (with `-`s replaced with `_`s)
#                         e.g. `docker-worker`/`generic-worker`.
#   workerConfig:         a dict to merge with generated workerConfig sections
#                         in generated worker pool definitions.
#
#
# AWS Image Sets
#
# AWS image sets must include the following:
#
# aws:
#   amis:
#     <region1>: <ami1>
#     <region2>: <ami2>
#     ...
#
#
# Google (gcp) Image Sets
#
# Google image sets include a single image, specified as follows:
#
# gcp:
#   image:                Fully qualified name of the machine image to spawn.
#                         e.g. `projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2019-11-04t22-31-35z`

generic-worker:
  workerImplementation: generic-worker
  # (this is intended for use with static workers)

docker-worker:
  workerImplementation: docker-worker
  gcp:
    image: projects/taskcluster-imaging/global/images/docker-worker-gcp-googlecompute-2020-03-12t12-33-33z

generic-worker-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0f1fe72cbcabc5891
      us-west-1: ami-0dddaece5e367895c
      us-west-2: ami-021217b1d0e9ae6d6
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-win2012r2-nefwcpqji22o4upodhz3
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/win2012r2/bootstrap.ps1

generic-worker-win2012r2-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-0162f92052875bf7e
      us-west-1: ami-0f6b26130f2f9ce2c
      us-west-2: ami-0dfd8045878e6cd08
  gcp:
    image: projects/community-tc-workers/global/images/generic-worker-win2012r2-staging-hasr18iepqtggvlswlku
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/mozilla/community-tc-config/ab5c8405d85c10ab7bc59c95d01463396fa3c623/imagesets/generic-worker-win2012r2-staging/bootstrap.ps1

generic-worker-ubuntu-18-04:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-02b7e7e5f63ce7dc3
      us-west-1: ami-005fd1b44bd56a762
      us-west-2: ami-0a77c8ffdc1f4fb5e
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux/bootstrap.sh

generic-worker-ubuntu-18-04-podman:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-079804c1ddb8cc957
      us-west-1: ami-0fa4594e78ca9c339
      us-west-2: ami-03c48f54cd54091c2
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://github.com/MozillaSecurity

generic-worker-ubuntu-18-04-staging:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-06ce1a5f3039ac646
      us-west-1: ami-0bd5b1b63c47a7b65
      us-west-2: ami-0a396cff215e28640
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: /etc/generic-worker/ed25519_key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: pmoore@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/ba5c21e60957f5ed3395f848f975a7ae8b147252/worker_types/gwci-linux-beta/bootstrap.sh

deepspeech-win2012r2:
  workerImplementation: generic-worker
  aws:
    amis:
      us-east-1: ami-09dd57282215e42ba
      us-west-1: ami-05696eedcf5032c65
      us-west-2: ami-02dfb5adb48a2032f
  workerConfig:
    genericWorker:
      config:
        ed25519SigningKeyLocation: C:\generic-worker\generic-worker-ed25519-signing-key.key
        shutdownMachineOnIdle: true
        idleTimeoutSecs: 90
        shutdownMachineOnInternalError: true
        workerTypeMetadata:
          machine-setup:
            maintainer: alissy@mozilla.com
            script: https://raw.githubusercontent.com/taskcluster/generic-worker/2509a1f8589b0b536186f5fe8f043385bf67197f/worker_types/deepspeech-win/bootstrap.ps1
